services:
  event-management-api:
    image: event_management_api
    container_name: event_management_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      LOG_LEVEL: DEBUG
      DB_URL: postgresql://postgres:postgres@postgres-db/event_management_db?connect_timeout=5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '256M'

  postgres-db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_management_db
    ports:
      - "15433:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1G'

volumes:
  postgres_data:
