"""added datat type to date for date column in event model

Revision ID: 0652c3be3c19
Revises: 926afd3761bb
Create Date: 2024-07-09 12:22:10.523481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0652c3be3c19'
down_revision: Union[str, None] = '926afd3761bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
