"""permission model refacto

Revision ID: 6ddbd90b0f5a
Revises: d094d0bce820
Create Date: 2024-07-25 01:23:32.696228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ddbd90b0f5a'
down_revision: Union[str, None] = 'd094d0bce820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_index('ix_permission_resource_name', table_name='permission')
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=False)
    op.drop_column('permission', 'method')
    op.drop_column('permission', 'resource_name')
    op.drop_column('permission', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('permission', sa.Column('resource_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('permission', sa.Column('method', postgresql.ENUM('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='httpmethodenum'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.create_index('ix_permission_resource_name', 'permission', ['resource_name'], unique=False)
    op.drop_column('permission', 'name')
    # ### end Alembic commands ###
