"""permission and roles model added description

Revision ID: c94179120948
Revises: 6ddbd90b0f5a
Create Date: 2024-07-25 01:51:07.415829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94179120948'
down_revision: Union[str, None] = '6ddbd90b0f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'description')
    op.drop_column('permission', 'description')
    # ### end Alembic commands ###
