"""added location field

Revision ID: cd71d7b5edf2
Revises: 0652c3be3c19
Create Date: 2024-07-09 14:53:25.336019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd71d7b5edf2'
down_revision: Union[str, None] = '0652c3be3c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.String(length=255), nullable=False))
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
